### ISSUE TITLE
Error after intersectBed step

### ISSUE THREAD

**Issue by alerubio** [gersteinlab/texp#1]
Hello.
I am getting the next ERROR after the intersectBed step:

make:~/tools/texp/library//L1HS_hg38/250000_35_0.1.prop.txt: Timestamp out of range; substituting 1970-01-01 01:00:00
make: ~/tools/texp/library//L1HS_hg38/250000_35_0.1.txt: Timestamp out of range; substituting 1970-01-01 01:00:00
2019-06-14(09:21:15) TeXP: There is another simulation running. Exiting without finishing.
exit 1
make: *** [~/tools/texp/library//L1HS_hg38/250000_35_0.1.txt] Error 1

Any idea?
Thanks and bests
Alejandro Rubio

**Comment by fabiocpn** [comment]
Dear Alex, 

One of the first steps in TeXP is to simulate full-length LINE-1 expression. The results of the simulation are generated at [texp_path]/library//L1HS_hg38/. In this specific case, you are simulating 35bp reads which are fairly short. To avoid issues in parallel running, **we only allow one simulation at a time.** 

That said, you only need to run the simulation once. After the first simulation, you can run TeXP in parallel. 

Thus our recommendation is to run a single instance of TeXP first, wait for the simulations to finish, and then process your RNA-seq data in parallel.

Best,
Fábio Navarro
