### ISSUE TITLE
Paired-end data

### ISSUE THREAD

**Issue by dborgesr** [gersteinlab/texp#4]
Hello,

This question might be answered in the documentation already (I apologize if i missed it).

Does Texp support paired end RNA-seq data?

--Thank you

**Comment by fabiocpn** [comment]
Dear Diego, 

No, TeXP only supports single-end RNA-seq data. We (empirically) found that, as one may expect, if the quality of the RNA-seq library is adequate, P1 and P2 yield very similar estimations. 

If that's the case, one could use only P1 reads or calculate the average between P1 and P2 to address paired-end reads.
