### ISSUE TITLE
Effective L1HS transcript lengths

### ISSUE THREAD

**Issue by yanwu2014** [gersteinlab/texp#6]
Hi! I was wondering how I could extract the L1Hs transcript lengths you guys used to compute RPKM from counts?

Thanks!
Yan

**Comment by fabiocpn** [comment]
Thank you for your interest, Yan. L1Hs transcripts should have ~6000 bases. Our estimates were derived from long-read RNA-seq. If I remember correctly, we used PacBio to estimate the average transcript length. There is no reason to believe that transcript length will dramatically differ between L1Hs, L1PA2, and L1PA3. 

Feel free to reach out if you have additional questions.
